### ISSUE TITLE
Login creds

### ISSUE THREAD

**Issue by gridworkz** [miguelrcDEV/mizo-erp-client#4]
Hi: How can I login to the system? Are there default creds?
Cheers,
Dave

**Comment by mizoRC** [comment]
You need the [server API](https://github.com/miguelrcDEV/mizo-erp-api). Once api is running, you can launch client, and there is a sign up button to create users

**Comment by gridworkz** [comment]
Yep, all that is running - I get the following screens:

![sc1](https://user-images.githubusercontent.com/19625672/95226283-bec06480-07ca-11eb-9a1f-0f16d14bd262.png)
![sc2](https://user-images.githubusercontent.com/19625672/95226285-bf58fb00-07ca-11eb-86e8-3d1afede650b.png)

**Comment by gridworkz** [comment]
....when I try to add / enter creds. Do I need to migrate data or anything?
Cheers, Dave

**Comment by mizoRC** [comment]
No, you have to add translations. This is a test project, and I don't have access to database because is already deleted. You can add using model [Translation](https://github.com/miguelrcDEV/mizo-erp-api/blob/master/models/Translation.js). And [here](https://github.com/miguelrcDEV/mizo-erp-client/blob/f93e57bdd34ed841afab0da9269f17dc808a41f9/src/components/Login/Login.jsx#L178) is how to use it
